package com.fatcat.nutrition.data;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

@Setter
@Getter
@JsonPropertyOrder({"id", "name", "kcal", "products"})
@Document(collection = "productLists")
@ApiModel(description = "data model of productList entity")
public class ProductList {

    @Id
    @ApiModelProperty(value = "productList id generated by db", position = 1)
    private String id;

    @ApiModelProperty(value = "productList name", position = 2)
    private String name;

    @DBRef
    @ApiModelProperty(value = "products in productList", position = 3)
    private List<Product> products;

    public ProductList() {
        products = new ArrayList<>();
    }

    public ProductList(String name) {
        this.name = name;
    }

    public void addProduct(Product product) {
        products.add(product);
    }

    @JsonProperty(value = "kcal")
    @ApiModelProperty(value = "total kcal of productList", position = 4)
    public int getTotalKcal() {
        return products.stream().mapToInt(Product::getKcal).sum();
    }

}
