package com.fatcat.nutrition.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


@Setter
@Getter
@Document(collection = "products")
@NoArgsConstructor
@ApiModel(description = "data model of product entity")
public class Product {

    @Id
    @ApiModelProperty(value = "product id generated by db", position = 1)
    private String id;

    @ApiModelProperty(value = "product name", position = 2)
    private String name;

    @ApiModelProperty(value = "product description", position = 3)
    private String description;

    @ApiModelProperty(value = "product kcal", position = 4)
    private int kcal;

    public Product(ProductDto productDto) {
        name = productDto.getName();
        description = productDto.getDescription();
        kcal = productDto.getKcal();
    }
}
